### ISSUE TITLE
Hypertext links on front page point to old address

### ISSUE THREAD

**Issue by justinar** [Jeffrey-P-McAteer/UMW_ACM_Programming_Challenge_Proctor#4]

**Comment by Jeffrey-P-McAteer** [comment]
Appears to be a caching problem, I checked and the cron task to update the doc is working properly. Open a private tab to http://54.84.84.136/ and you will find the document is up to date, but my browser serves a cached version.
I'll look into how Nginx caches documents, I noticed an etag and If-Modified-Since tags on the request.

**Comment by justinar** [comment]
Working right again, maybe my cache expired
